# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JrnlSync < Formula
  desc "Faciliatates automatic sync of jrnl notes to external sources"
  homepage "https://www.github.com/jm96441n/jrnlSync"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "http://github.com/jm96441n/jrnlSync/releases/v1.0.0/jrnlSync_1.0.0_Darwin_arm64.tar.gz"
      sha256 "b92080d0be5e5d90dc36b944b9375f085c0db7a55be1c38a396cc786635c50de"

      def install
        bin.install "jrnlSync"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/jm96441n/jrnlSync/releases/v1.0.0/jrnlSync_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "46014ef20521f1f8719c49f01b6e89f496d9661b1781ce3a3bd28c0b27c8e4a8"

      def install
        bin.install "jrnlSync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/jm96441n/jrnlSync/releases/v1.0.0/jrnlSync_1.0.0_Linux_arm64.tar.gz"
      sha256 "bec19de88a560a0e99407dd8720fc7d6ebc16849ee21aa9dd63a30aebb7f1b17"

      def install
        bin.install "jrnlSync"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/jm96441n/jrnlSync/releases/v1.0.0/jrnlSync_1.0.0_Linux_x86_64.tar.gz"
      sha256 "27e7cf896457d823d215bfa85219e85b27d6628cbfecfd546c8f83677392a286"

      def install
        bin.install "jrnlSync"
      end
    end
  end
end
